services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80" # Opcional se usar apenas via Tunnel, mas Ãºtil para debug local
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/conf.d:ro
    networks:
      - proxy-net
    # Adiciona o host.docker.internal no Linux para acessar o Frigate na porta 5000 do host
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  proxy-net:
    external: true