
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.23.0.0/16  
    - 127.0.0.1
    - ::1

rest_command:
  notificar_whatsapp_campainha:
    # Use o IP local do servidor onde roda o Docker (ex: 192.168.0.X)
    # E a porta mapeada no docker-compose (geralmente 3000)
    url: "http://192.168.0.200:3000/whatsapp/doorbell" 
    method: POST
    content_type: "application/json"
    payload: '{"camera": "cam_13"}'